println("poop")
#for more codes  on my profile
fmkldsjmfklskfd
fmkldsjmfklskfdf
dsfd
dsfdfd
fmkldsjmfklskfdfds
fmkldsjmfklskfdfd\s
fsd\
fsdf
dsfdds
fmkldsjmfklskfdd
fsdsdfdsfdsfds
fd
sf
dsfddsfdsf
dsfddsfdsfds
fsdsdfdsfdsfdsfs
dsfddsfdsfsdf
ds
fsdsdfdsfdsfdsfsd
fsdsdfdsfdsfdsf\ds
fsdsfsdffdsfndskjfdsjkhfkjdsjklfjdksljfds
fnhndskjhfsjldshjfldsjklfjdkslf
'dslkfndslflkdsjklfjdklsf]
